cmd_/home/topeet/itop/30-usb_wifi_MT7601U/DPO_MT7601U_LinuxSTA_3.0.0.4_20130913/os/linux/../../rate_ctrl/alg_ags.o := arm-linux-gnueabi-gcc -Wp,-MD,/home/topeet/itop/30-usb_wifi_MT7601U/DPO_MT7601U_LinuxSTA_3.0.0.4_20130913/os/linux/../../rate_ctrl/.alg_ags.o.d  -nostdinc -isystem /usr/lib/gcc/arm-linux-gnueabi/4.6/include -I/home/topeet/android/iTop4412_Kernel_3.0/arch/arm/include -Iarch/arm/include/generated -Iinclude  -include include/generated/autoconf.h -D__KERNEL__ -mlittle-endian -Iarch/arm/mach-exynos/include -Iarch/arm/plat-s5p/include -Iarch/arm/plat-samsung/include -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -mtune=cortex-a9 -march=armv7-a -mfpu=neon -O2 -marm -fno-dwarf2-cfi-asm -fno-omit-frame-pointer -mapcs -mno-sched-prolog -mabi=aapcs-linux -mno-thumb-interwork -D__LINUX_ARM_ARCH__=7 -march=armv7-a -msoft-float -Uarm -Wframe-larger-than=1024 -fno-stack-protector -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -g -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -DCC_HAVE_ASM_GOTO -DAGGREGATION_SUPPORT -DPIGGYBACK_SUPPORT -DWMM_SUPPORT -DLINUX -Wall -Wstrict-prototypes -Wno-trigraphs -DSYSTEM_LOG_SUPPORT -DRT28xx_MODE=STA -DCHIPSET=7601U -DRESOURCE_PRE_ALLOC -I/home/topeet/itop/30-usb_wifi_MT7601U/DPO_MT7601U_LinuxSTA_3.0.0.4_20130913/include -DCONFIG_STA_SUPPORT -DSCAN_SUPPORT -DDBG -DWPA_SUPPLICANT_SUPPORT -DNATIVE_WPA_SUPPLICANT_SUPPORT -DDOT11_N_SUPPORT -DDOT11N_DRAFT3 -DSTATS_COUNT_SUPPORT -DMT7601U -DMT7601 -DRLT_MAC -DRLT_RF -DRTMP_MAC_USB -DRTMP_USB_SUPPORT -DRTMP_TIMER_TASK_SUPPORT -DRX_DMA_SCATTER -DVCORECAL_SUPPORT -DRTMP_EFUSE_SUPPORT -DNEW_MBSSID_MODE -DRTMP_INTERNAL_TX_ALC -DCONFIG_ANDES_SUPPORT -DDPD_CALIBRATION_SUPPORT -DCONFIG_RX_CSO_SUPPORT -DRTMP_FREQ_CALIBRATION_SUPPORT  -DMODULE -fno-pic -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(alg_ags)"  -D"KBUILD_MODNAME=KBUILD_STR(mt7601Usta)" -c -o /home/topeet/itop/30-usb_wifi_MT7601U/DPO_MT7601U_LinuxSTA_3.0.0.4_20130913/os/linux/../../rate_ctrl/alg_ags.o /home/topeet/itop/30-usb_wifi_MT7601U/DPO_MT7601U_LinuxSTA_3.0.0.4_20130913/os/linux/../../rate_ctrl/alg_ags.c

source_/home/topeet/itop/30-usb_wifi_MT7601U/DPO_MT7601U_LinuxSTA_3.0.0.4_20130913/os/linux/../../rate_ctrl/alg_ags.o := /home/topeet/itop/30-usb_wifi_MT7601U/DPO_MT7601U_LinuxSTA_3.0.0.4_20130913/os/linux/../../rate_ctrl/alg_ags.c

deps_/home/topeet/itop/30-usb_wifi_MT7601U/DPO_MT7601U_LinuxSTA_3.0.0.4_20130913/os/linux/../../rate_ctrl/alg_ags.o := \
    $(wildcard include/config/sta/support.h) \

/home/topeet/itop/30-usb_wifi_MT7601U/DPO_MT7601U_LinuxSTA_3.0.0.4_20130913/os/linux/../../rate_ctrl/alg_ags.o: $(deps_/home/topeet/itop/30-usb_wifi_MT7601U/DPO_MT7601U_LinuxSTA_3.0.0.4_20130913/os/linux/../../rate_ctrl/alg_ags.o)

$(deps_/home/topeet/itop/30-usb_wifi_MT7601U/DPO_MT7601U_LinuxSTA_3.0.0.4_20130913/os/linux/../../rate_ctrl/alg_ags.o):
